/** Declaration file generated by dts-gen */

declare module "blakejs" {

  export function blake2b(input: string | Uint8Array, key?: Uint8Array | undefined, outlen?: number): Uint8Array;
}

declare module "oo7-substrate" {

  export  function srKeypairFromUri(url: string): any;
  // @ts-ignore
  export  let calls = {};

   export  function encode(value: any[], type: any): any;

}
